<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>BnPRelay</AssemblyName>
    <RootNamespace>BnPRelay</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Lightweight Framework-Dependent Single-File Binary (< 1.5 MB!) -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <ApplicationIcon>UI\Assets\heart.ico</ApplicationIcon>
    <Version>1.2.16</Version>
    <AssemblyVersion>1.2.16.0</AssemblyVersion>
    <FileVersion>1.2.16.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="UI\Assets\**\*" />
    <EmbeddedResource Include="Setup\GameManifest.json" />
  </ItemGroup>

</Project>
